

DEFINES *= BOOST_ALL_DYN_LINK
DEFINES *= BOOST_ALL_NO_LIB
DEFINES *= BOOST_THREAD_PROVIDES_FUTURE_CTOR_ALLOCATORS
DEFINES *= BOOST_THREAD_VERSION=4
DEFINES *= BOOST_REGEX_NO_EXTERNAL_TEMPLATES

win32{
    DEFINES *= _WIN32_WINNT=0x0601
}
